[project]
name = "deepseek-quickstart"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openai>=2.15.0",
    "requests>=2.32.5",
    "tqdm>=4.67.1",
]
